### ISSUE TITLE
About bundle_adjust and dsmr package

### ISSUE THREAD

**Issue by LHDuan** [centreborelli/satnerf#1]
Thanks for your excellent work.
I have some problems with the package installation.
1. It seems that the bundle_adjust package is not available yet. I can't open the link (https://github.com/centreborelli/sat-bundleadjust).
2. Can you show how to install the dsmr package. I can't find any information about it on the internet.

Looking forward to your reply, thanks!

**Comment by rogermm14** [comment]
Hello, thank you for your message :)

Here are some clarifications:
1. Both packages *bundle_adjust* and *dsmr* concern optional bricks of the project. The only conda environment that is strictly necessary to install to test/train the model is satnerf. We used *bundle_adjust* to refine the RPC camera models of the training/test images, but you can simply download such data directly from the [EarthVision 2022 release](https://github.com/centreborelli/satnerf/releases/tag/EarthVision2022) of the code. Of course, you can also use unrefined camera models, at the expense of some loss in accuracy.

2. https://github.com/centreborelli/sat-bundleadjust should now be public. Check our related [paper](https://www.ipol.im/pub/art/2021/352/) for an explanation of this bundle adjustment methodology for the RPC functions of satellite images.

3. *dsmr* is not yet public but you will simply get a warning message when you run the code, along with a rough approximation of the altitude MAE. We are working to remove the *dsmr* dependency of the code soon.

Let me know if you run into any further issues !
