### ISSUE TITLE
How to crop the images of DFC-2019 dataset

### ISSUE THREAD

**Issue by jieeeeeeeeeee** [centreborelli/satnerf#10]
This project is challenging and meaningful, and the code is very effective.
I find that the small-size images will get a good result. So I want to know how to corp the *tif image in the DFC-2019 dataset and ensure the RPC parameters are updated correctly.
How to crop images as the images in the Track3-RGB-crops folder.
![image](https://user-images.githubusercontent.com/31924229/201361132-5471bd43-c11a-4839-ab79-9489e79b83fb.png)

Thanks. :)

**Comment by wuy202** [comment]
There's a "create_satellite_dataset" function in create_satellite_dataset.py, inside it, "crop_geotiff_lonlat_aoi" is used to crop satellite images and RPCs.

**Comment by jieeeeeeeeeee** [comment]
Many thanks. :)
