### ISSUE TITLE
If I use the data set you provided, do I need to perform bundle_adjust again?

### ISSUE THREAD

**Issue by ZhouWeikun** [centreborelli/satnerf#15]
First, thanks for your work.
But I have some questions about the data set used during training. If I use the data set you provided that contains 4 JAX scenes, do I need to perform bundle_adjust again?

**Comment by rogermm14** [comment]
Hello,
There is no need to perform bundle_adjust again to replicate the experiments.
The bundle adjusted RPC camera models can be found in the `dataset/crops_rpcs_ba_v2` directory of the dataset.
Best,
Roger
