### ISSUE TITLE
[Help] The definition of `predefined_val_ts`?

### ISSUE THREAD

**Issue by DapengFeng** [centreborelli/satnerf#16]
Hi, thank you for the excellent work. After reading the paper and the code, I am still confused about the definition of `predefined_val_ts`. Could you give suggestions for applying to other scenes in `DFC2019`?
https://github.com/centreborelli/satnerf/blob/de7bd6ec1cbd6f3895949350d6ca98ba56e87bdd/eval_satnerf.py#L186-L209

**Comment by rogermm14** [comment]
Hello! Thank you for your comment.
Sat-NeRF uses the index of each input image in the training set to learn a transient embedding.
Validation images are not part of the training set, so there are different ways to handle them: e.g., do not use any transient embedding, or assign them a random index or a predefined index.
With `predefined_val_ts`, I simply fixed the selected image indexes for the validation views, but you can use any of the choices I listed, there is no correct way to do it.
Best,
Roger

**Comment by DapengFeng** [comment]
Dear Roger,

Thank you for your reply.  Does it mean that the value of `predefined_val_ts` has no effect on the validation performance?

Best,
Dapeng

**Comment by rogermm14** [comment]
Exactly, `predefined_val_ts` does not alter the output rgb values or the output geometry. PSNR and elevation MAE will not be affected.
Best,
Roger

**Comment by DapengFeng** [comment]
Well, that is cool. Thank you.

**Comment by zakiindra** [comment]
Hi @rogermm14 sorry for asking this again. Does it mean for any other AOI, we can fix the predefined_val_ts to any number, and the validation metrics wouldn't be affected?
