### ISSUE TITLE
How would I go about making my own dataset?

### ISSUE THREAD

**Issue by MaverickDSmith** [centreborelli/satnerf#17]
I see that the dataset loader is hard-coded to work with the JAX dataset. Are there any tools for using my own .geotiff files with RPC camera models or scripts available that could be shared?

**Comment by rogermm14** [comment]
Hello,

Thanks for your interest.
I think the best way to try other datasets is to create a new script equivalent to `create_satellite_dataset.py` that generates the same type of json files from your own geotiff files. Most of the code from `create_satellite_dataset.py` can be reused for that. To be more generic you can rewrite it to accept an area of interest (AOI) in longitude and latitude coords and the paths to the input geotiff files + RPCs. 

Things to keep in mind:

- We worked with AOIs of 256x256 meters for the paperl, not the entire images.
- If you want to use Sat-NeRF on raw satellite images, you will probably have to add some color preprocessing for an optimal performance. Most likely a pansharpening and/or color correction is required in addition to the bundle adjustment of RPCs that we cover with [sat-bundleadjust](https://github.com/centreborelli/sat-bundleadjust) . The color of the Jacksonville images that we tested is already preprocessed so we did not code any tools for that.

Best,
Roger
