### ISSUE TITLE
Some problems with running the program

### ISSUE THREAD

**Issue by xczbecalm** [centreborelli/satnerf#2]
Thank you for sharing the latest achievements with us.
I tried to reproduce your results, but encountered some problems, hope you can help :

1. I used Anaconda to create a virtual environment in The Windows system and installed the corresponding library as required, but **plyflatten** library always failed to be installed successfully. The error was reported during the building Wheel for many times: 
         ERROR: Could not build wheels for plyflatten, which is required to install pyproject.toml-based projects
I tried many ways to solve the problem, but to no avail.
2. I tried to run the code in Google Colab again, and the plyFlatten library problem no longer appeared, but unfortunately there was a new problem: 
     pyproj.exceptions.CRSError: Invalid projection: +proj=utm +zone=17R +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone)
This error occurs at line 109 of sat_util.py: 
     proj_dst = pyproj.Proj("+proj=utm +zone={}{}".format(n, l))

Looking forward to your reply, thanks!

**Comment by YK-hastur** [comment]
> 
im also run this on windows, for first question, i reconstract plyflatten`s src\*.c file and use gcc compile to .dll, for second question, follow my code may solve: 
......
    n = utm.latlon_to_zone_number(lats[0], lons[0])
    # l = utm.latitude_to_zone_letter(lats[0])
    n = utm.conversion.zone_number_to_central_longitude(n)
    proj_src = pyproj.Proj("+proj=latlong")
    proj_dst = pyproj.Proj("+proj=utm +zone={}".format(n))
......

**Comment by xczbecalm** [comment]
> > 
> 
> im also run this on windows, for first question, i reconstract plyflatten`s src*.c file and use gcc compile to .dll, for second question, follow my code may solve: ...... n = utm.latlon_to_zone_number(lats[0], lons[0]) # l = utm.latitude_to_zone_letter(lats[0]) n = utm.conversion.zone_number_to_central_longitude(n) proj_src = pyproj.Proj("+proj=latlong") proj_dst = pyproj.Proj("+proj=utm +zone={}".format(n)) ......

Thank you for your reply!
By consulting the data, I solved the second problem. The solution to the second problem you provided is exactly right.
As for the installation of PlyFlatten library, I will try the solution you provided at once, sincerely thank you!

**Comment by rogermm14** [comment]
Thank you for your comments. Unfortunately, the code was developed with ubuntu and we never tested it on windows.

**Comment by Eunjnnn** [comment]
> Thank you for sharing the latest achievements with us. I tried to reproduce your results, but encountered some problems, hope you can help :
> 
> 1. I used Anaconda to create a virtual environment in The Windows system and installed the corresponding library as required, but **plyflatten** library always failed to be installed successfully. The error was reported during the building Wheel for many times:
>    ERROR: Could not build wheels for plyflatten, which is required to install pyproject.toml-based projects
>    I tried many ways to solve the problem, but to no avail.
> 2. I tried to run the code in Google Colab again, and the plyFlatten library problem no longer appeared, but unfortunately there was a new problem:
>    pyproj.exceptions.CRSError: Invalid projection: +proj=utm +zone=17R +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone)
>    This error occurs at line 109 of sat_util.py:
>    proj_dst = pyproj.Proj("+proj=utm +zone={}{}".format(n, l))
> 
> Looking forward to your reply, thanks!

I have same issue with you (problem 1 : ERROR: Could not build wheels for plyflatten, which is required to install pyproject.toml-based projects ) ,,,!!
Have you solve the issue??  Please let me know 😢

**Comment by wtj-zhong** [comment]
Can you give me a specific version? I am python3.6 appeared python3 eval_satnerf.py Sat-NeRF $pretrained_models/JAX_068 out_eval_path/JAX_068 28 val $pretrained_models/JAX_068 $dataset_dir/root_dir/crops_rpcs_ba_v2/JAX_068 $dataset_dir/DFC2 019/Track3-RGB-crops/JAX_068 $dataset_dir/ DFC2019/Track3-Truth
/home/wtj/anaconda3/envs/satnerf/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.0.0)/charset_normalizer (2.0.12 ) doesn't match a supported version!
  question
