### ISSUE TITLE
How ts in predefined_val_ts is generated for each AOI?

### ISSUE THREAD

**Issue by zakiindra** [centreborelli/satnerf#23]
I have been generating new datasets using `create_satellite_datasets` from DFC2019. I have generated metadata JSON and cropped images but still missing predefined ts declared in `predefined_val_ts(img_id)` function. I don't understand how the ts values for each image ID are generated. Can you explain how those values are generated for each image ID?

**Comment by rogermm14** [comment]
Hello @zakiindra, 
This issue was previously discussed here: https://github.com/centreborelli/satnerf/issues/16
