### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by DapengFeng** [centreborelli/satnerf#3]

**Comment by rogermm14** [comment]
Hello, if you only want to visualize results you can use the `eval_satnerf.py` script as indicated in the readme.
I have just pushed some minor changes to remove some hardcoded paths that were disturbing.

Here are some more specific instructions.

1) Download the DFC2019 data and the pretrained models from the [2022 EarthVision release](https://github.com/centreborelli/satnerf/releases/tag/EarthVision2022).
2) To make things easier, you can set $path_to_pretrained_models and $path_to_dataset pointing to the previous downloaded directories.
2) Make sure you have installed the satnerf environment: `conda init && bash -i setup_satnerf_env.sh` 
3) Use `eval_satnerf.py`. For instance, let's test Sat-NeRF for area JAX_068. Epoch 28 is available in the pretrained models (file "epoch=27.ckpt"). The command would be the following then:

`python3 eval_satnerf.py Sat-NeRF $path_to_pretrained_models/JAX_068 output_path 28 val $path_to_pretrained_models/JAX_068 $path_to_dataset/root_dir/crops_rpcs_ba_v2/JAX_068 $path_to_dataset/DFC2019/Track3-RGB-crops/JAX_068 $path_to_dataset/DFC2019/Track3-Truth`

This will write all the output images in the output_path. They are written in .tif format.
Let me know if you run into any further issues!
