### ISSUE TITLE
Error related to t_embbeding_vocab

### ISSUE THREAD

**Issue by zakiindra** [centreborelli/satnerf#36]
The description for `--first_beta_epoch`, `--t_embbeding_tau`, `--t_embbeding_vocab` are all the same with `ds_drop`. I am not sure if their description are correct.
https://github.com/centreborelli/satnerf/blob/master/opt.py#L72
https://github.com/centreborelli/satnerf/blob/master/opt.py#L74
https://github.com/centreborelli/satnerf/blob/master/opt.py#L76

Context:
 I had issues with either `t_embbeding_vocab` or `t_embbeding_tau` which caused an error in CUDA when I ran satnerf model for Omaha data. Almost all scenes in Omaha data consists of more than 30 images, and I believe setting the default embedding vocab to 30 might be the root cause of the issue. I don't what `t_embbeding_vocab` is, so I need to know in more details about it.

Here is the CUDA error:
```
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:605: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=710 : device-side assert triggered
Traceback (most recent call last):
```

It happens when executing `rays_t = models['t'](ts) if ts is not None else None` in rendering.py

**Comment by tehret** [comment]
I clarified the option descriptions. 

`t_embbeding_vocab` corresponds to the number of image specific embeddings defined during the creation of the model. 
The error means that you're trying to access an embedding that doesn't exist so either this parameter is smaller than the number of training images or you're trying to access an embedding that doesn't exist during evaluation.
