### ISSUE TITLE
Poor DSM within water areas

### ISSUE THREAD

**Issue by wuy202** [centreborelli/satnerf#5]
Quality of DSMs generated using Sat-NeRF is pretty bad when it comes to water areas, any solution to such problem and what might be the reason that cause this error ?

**Comment by rogermm14** [comment]
Hello,
As explained in the papers, NeRF and Sat-NeRF require radiometric consistency to infer geometry. Water areas have no radiometric consistency, so it should not be a surprise that the geometry is erroneous there. If you are using the [DFC2019](https://ieee-dataport.org/open-access/data-fusion-contest-2019-dfc2019) data, semantic segmentation is available including water labels. If you are using your own data, I would suggest that you first detect the water areas in your satellite images and then mask the output NeRF/SatNeRF DSMs accordingly.
