### ISSUE TITLE
Can I derive a 3D obj model for mapping?

### ISSUE THREAD

**Issue by 1zgh** [centreborelli/satnerf#8]

**Comment by rogermm14** [comment]
You can use the DSM (.tif file) generated by `create_satnerf_dsm.py` for this. But the conversion from .tif to 3D formats like .obj or .ply is not part of this code. There are multiple online tools for that, you can check [this discussion](https://gis.stackexchange.com/questions/121561/seeking-tool-to-generate-mesh-from-dtm) for instance.

**Comment by 1zgh** [comment]
Thanks!
